[package]
name = "ckb-notify"
version = "0.19.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
fnv = "1.0"
ckb-types = { path = "../util/types" }
crossbeam-channel = "0.3"
ckb-stop-handler = { path = "../util/stop-handler" }
ckb-logger = { path = "../util/logger" }
