[package]
name = "ckb-reward-calculator"
version = "0.19.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-types = { path = "../types" }
ckb-store = { path = "../../store" }
failure = "0.1.5"
ckb-dao = { path = "../dao" }
ckb-logger = { path = "../logger" }
ckb-chain-spec = {path = "../../spec"}

[dev-dependencies]
ckb-chain-spec = { path = "../../spec" }
ckb-db = { path = "../../db" }
ckb-script = { path = "../../script" }
ckb-occupied-capacity = { path = "../occupied-capacity" }
