[package]
name = "ckb-jsonrpc-types"
version = "0.19.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-types = { path = "../types" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
faster-hex = "0.3"
jsonrpc-core = "10.1"

[dev-dependencies]
proptest = "0.9"
