[package]
name = "ckb-chain-spec"
version = "0.19.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
ckb-types = { path = "../util/types" }
ckb-pow = { path = "../pow" }
ckb-resource = { path = "../resource" }
ckb-occupied-capacity = { path = "../util/occupied-capacity" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }
ckb-dao-utils = { path = "../util/dao/utils" }
