[package]
name = "ckb-script"
version = "0.19.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-script-data-loader = { path = "data-loader" }
byteorder = "1.3.1"
ckb-types = {path = "../util/types"}
ckb-hash = {path = "../util/hash"}
ckb-vm = { version = "0.15.1", features = ["asm"] }
faster-hex = "0.3"
fnv = "1.0.3"
ckb-logger = { path = "../util/logger" }
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
proptest = "0.9"
ckb-db = { path = "../db" }
ckb-store = { path = "../store" }
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
tiny-keccak = "1.4"
ckb-crypto = { path = "../util/crypto"}
