[package]
name = "ckb-chain"
version = "0.19.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
ckb-logger = { path = "../util/logger" }
ckb-types = { path = "../util/types" }
ckb-shared = { path = "../shared" }
ckb-chain-spec = { path = "../spec" }
ckb-store = { path = "../store" }
ckb-notify = { path = "../notify" }
ckb-verification = { path = "../verification" }
faketime = "0.2.0"
crossbeam-channel = "0.3"
ckb-stop-handler = { path = "../util/stop-handler" }
lru-cache = { git = "https://github.com/nervosnetwork/lru-cache", rev = "a35fdb8" }
ckb-traits = { path = "../traits" }
failure = "0.1.5"
ckb-dao = { path = "../util/dao" }

[dev-dependencies]
env_logger = "0.6"
tempfile = "3.0"
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
ckb-dao-utils = { path = "../util/dao/utils" }
