[package]
name = "ckb-benches"
version = "0.33.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]


[dev-dependencies]
criterion = "0.3"
ckb-chain = { path = "../chain" }
ckb-types = { path = "../util/types" }
ckb-shared = { path = "../shared" }
ckb-store = { path = "../store" }
ckb-chain-spec = { path = "../spec" }
rand = "0.7"
ckb-hash = {path = "../util/hash"}
ckb-test-chain-utils = { path = "../util/test-chain-utils" }
ckb-dao-utils = { path = "../util/dao/utils" }
ckb-dao = { path = "../util/dao" }
ckb-system-scripts = { version = "= 0.5.1" }
lazy_static = "1.3.0"
ckb-crypto = { path = "../util/crypto" }
faketime = "0.2.0"
ckb-jsonrpc-types = { path = "../util/jsonrpc-types" }
ckb-verification = { path = "../verification" }
ckb-app-config = { path = "../util/app-config" }
ckb-fee-estimator = { path = "../util/fee-estimator" }

[[bench]]
name = "bench_main"
harness = false

[features]
default = []
ci = []
