[package]
name = "ckb-types"
version = "0.19.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
molecule = "0.2.0"
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
numext-fixed-uint = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
bytes = { version="0.4.12", features = ["serde"] }
ckb-occupied-capacity = { path = "../occupied-capacity" }
ckb-hash = { path = "../hash" }
ckb-merkle-tree = { path = "../merkle-tree" }
crossbeam-channel = "0.3"
bit-vec = "0.5.1"
failure = "0.1.5"
